from .subfinder import SubfinderCollector
from .httpx import HttpxCollector
from .katana import KatanaCollector
from .javascript import JavaScriptCollector
from .nuclei import NucleiCollector
from .technology import TechnologyCollector
from .takeover import SubdomainTakeoverCollector
from .information_disclosure import InformationDisclosureCollector, SecretExtractor
from .access_control import AccessControlCollector
from .path_traversal import PathTraversalCollector
from .sql_injection import SQLInjectionCollector, SQLInjectionAnalyzer, SQLInjectionPayloadGenerator
from .xss import XSSCollector, XSSAnalyzer, XSSPayloadGenerator, XSSContext
from .command_injection import (
    CommandInjectionCollector,
    CommandInjectionPayloadGenerator,
    CommandInjectionAnalyzer,
    CommandInjectionResult,
)
from .ssrf import (
    SSRFCollector,
    SSRFPayloadGenerator,
    SSRFAnalyzer,
    SSRFResult,
    SSRFTechnique,
    SSRFCloudProvider,
    Severity,
)
from .oauth import (
    OAuthCollector,
    OAuthPayloadGenerator,
    OAuthAnalyzer,
    TokenValidationAnalyzer,
    SessionSecurityAnalyzer,
)
from .xml_parser import (
    XMLParserSecurityCollector,
    XMLParserValidationCollector,
    XXECollector,
    XMLPayloadGenerator,
    XMLParserAnalyzer,
    XMLValidationResult,
    XMLTechnique,
    XMLMutationStrategy,
)
from .deserialization import (
    DeserializationCollector,
    InsecureDeserializationCollector,
    DeserializationValidationCollector,
    DeserializationPayloadGenerator,
    DeserializationAnalyzer,
    DeserializationResult,
    DeserializationFormat,
    DeserializationTechnique,
    DeserializationMutationStrategy,
)
from .graphql import (
    GraphQLSecurityCollector,
    GraphQLCollector,
    GraphQLPayloadGenerator,
    GraphQLSecurityAnalyzer,
    GraphQLSecurityResult,
    GraphQLSeverity,
    GraphQLTechnique,
    GraphQLMutationStrategy,
)
from .websocket import (
    WebSocketSecurityCollector,
    WebSocketCollector,
    WebSocketPayloadGenerator,
    WebSocketSecurityAnalyzer,
    WebSocketSecurityResult,
    WebSocketSeverity,
    WebSocketTechnique,
    WebSocketMutationStrategy,
)
from .request_smuggling import (
    HTTPRequestSmugglingCollector,
    RequestSmugglingCollector,
    RequestSmugglingPayloadGenerator,
    RequestSmugglingSecurityAnalyzer,
    RawHttpStreamProber,
    RawHttpResponse,
    RequestSmugglingResult,
    RequestSmugglingSeverity,
    RequestSmugglingTechnique,
    RequestSmugglingMutationStrategy,
)
from .race_conditions import (
    RaceConditionsCollector,
    RaceConditionCollector,
    RaceConditionPayloadGenerator,
    RaceConditionSecurityAnalyzer,
    ConcurrencyProber,
    ConcurrencyProbeResponse,
    RaceConditionResult,
    RaceConditionSeverity,
    RaceConditionTechnique,
    ConcurrencyStrategy,
)
from .business_logic import (
    BusinessLogicCollector,
    BusinessLogicFlawsCollector,
    BusinessLogicPayloadGenerator,
    BusinessLogicSecurityAnalyzer,
    StatefulWorkflowProber,
    BusinessLogicResult,
    BusinessLogicSeverity,
    BusinessLogicTechnique,
    BusinessLogicMutationStrategy,
    WorkflowStep,
    WorkflowSequence,
    BusinessLogicProbe,
    BusinessLogicProbeResponse,
)
from .ssti import (
    SSTICollector,
    ServerSideTemplateInjectionCollector,
    SSTIPayloadGenerator,
    SSTISecurityAnalyzer,
    SSTIProber,
    SSTIProbe,
    SSTIProbeResponse,
    SSTIResult,
    SSTISeverity,
    SSTITechnique,
    SSTIEngineFamily,
    SSTIMutationStrategy,
)
from .cache_security import (
    CacheSecurityCollector,
    WebCachePoisoningCollector,
    CachePoisoningCollector,
    WebCacheDeceptionCollector,
    CacheSecurityPayloadGenerator,
    CacheSecurityProber,
    CacheSecurityAnalyzer,
    CacheProbe,
    CacheProbeResponse,
    CacheSecurityResult,
    CacheVulnerabilityType,
    CacheSecurityTechnique,
    CacheEngineFamily,
    CacheEngine,
    CacheStatus,
    CacheMutationStrategy,
    CacheSecurityMutationStrategy,
    CacheSecuritySeverity,
)
# CORS / security-header detection is provided by the canonical, tested collector
# in cors_security.py. The former cors_headers.py rewrite had no consumers and no
# tests; it is retired to a deprecation shim. The historical collector-variant
# names are kept as backward-compatible aliases of the single CORSSecurityCollector.
from .cors_security import (
    CORSSecurityCollector,
    CORSSecurityAnalyzer,
    CORSPayloadGenerator,
    CORSProbe,
    CORSProbeResponse,
    CORSSecurityResult,
    HeaderAuditResult,
    CORSVulnerabilityType,
    HeaderVulnerabilityType,
    CORSMutationStrategy,
)

CORSHeadersCollector = CORSSecurityCollector
CORSCollector = CORSSecurityCollector
CORSMisconfigurationCollector = CORSSecurityCollector
HTTPHeaderAuditorCollector = CORSSecurityCollector
SecurityHeadersCollector = CORSSecurityCollector
HTTPHeaderCollector = CORSSecurityCollector
CORSAnalyzer = CORSSecurityAnalyzer
from .auth_bypass import (
    AuthBypassCollector,
    AuthenticationBypassCollector,
    CredentialAttackCollector,
    BruteForceCollector,
    DefaultCredentialsCollector,
    JWTMisconfigurationCollector,
    MFABypassCollector,
    SessionFixationCollector,
    AuthCollector,
    AuthBypassPayloadGenerator,
    AuthBypassProber,
    AuthBypassAnalyzer,
    TokenEntropyAnalyzer,
    AuthBypassProbe,
    AuthBypassProbeResponse,
    AuthBypassResult,
    AuthVulnerabilityType,
    AuthBypassTechnique,
    AuthTechnique,
    AuthMutationStrategy,
    AuthBypassMutationStrategy,
    AuthStrategy,
    AuthBypassSeverity,
    AuthSeverity,
)
from .prototype_pollution import (
    PrototypePollutionCollector,
    ClientSideAttackCollector,
    DOMClobberingCollector,
    OpenRedirectCollector,
    ClickjackingCollector,
    ProtoPollutionCollector,
    PrototypePollutionPayloadGenerator,
    PrototypePollutionProber,
    PrototypePollutionAnalyzer,
    PrototypePollutionProbe,
    PrototypePollutionProbeResponse,
    PrototypePollutionResult,
    ClientSideAttackResult,
    PrototypePollutionVulnerabilityType,
    ClientSideVulnerabilityType,
    PrototypePollutionTechnique,
    ClientSideTechnique,
    PrototypePollutionMutationStrategy,
    ClientSideMutationStrategy,
    PrototypePollutionStrategy,
    ClientSideStrategy,
    PrototypePollutionSeverity,
    ClientSideSeverity,
    GadgetFramework,
)



__all__ = [
    "SubfinderCollector",
    "HttpxCollector",
    "KatanaCollector",
    "JavaScriptCollector",
    "NucleiCollector",
    "TechnologyCollector",
    "SubdomainTakeoverCollector",
    "InformationDisclosureCollector",
    "SecretExtractor",
    "AccessControlCollector",
    "PathTraversalCollector",
    "SQLInjectionCollector",
    "SQLInjectionAnalyzer",
    "SQLInjectionPayloadGenerator",
    "XSSCollector",
    "XSSAnalyzer",
    "XSSPayloadGenerator",
    "XSSContext",
    "CommandInjectionCollector",
    "CommandInjectionPayloadGenerator",
    "CommandInjectionAnalyzer",
    "CommandInjectionResult",
    "SSRFCollector",
    "SSRFPayloadGenerator",
    "SSRFAnalyzer",
    "SSRFResult",
    "SSRFTechnique",
    "SSRFCloudProvider",
    "Severity",
    "OAuthCollector",
    "OAuthPayloadGenerator",
    "OAuthAnalyzer",
    "TokenValidationAnalyzer",
    "SessionSecurityAnalyzer",
    "XMLParserSecurityCollector",
    "XMLParserValidationCollector",
    "XXECollector",
    "XMLPayloadGenerator",
    "XMLParserAnalyzer",
    "XMLValidationResult",
    "XMLTechnique",
    "XMLMutationStrategy",
    "DeserializationCollector",
    "InsecureDeserializationCollector",
    "DeserializationValidationCollector",
    "DeserializationPayloadGenerator",
    "DeserializationAnalyzer",
    "DeserializationResult",
    "DeserializationFormat",
    "DeserializationTechnique",
    "DeserializationMutationStrategy",
    "GraphQLSecurityCollector",
    "GraphQLCollector",
    "GraphQLPayloadGenerator",
    "GraphQLSecurityAnalyzer",
    "GraphQLSecurityResult",
    "GraphQLSeverity",
    "GraphQLTechnique",
    "GraphQLMutationStrategy",
    "WebSocketSecurityCollector",
    "WebSocketCollector",
    "WebSocketPayloadGenerator",
    "WebSocketSecurityAnalyzer",
    "WebSocketSecurityResult",
    "WebSocketSeverity",
    "WebSocketTechnique",
    "WebSocketMutationStrategy",
    "HTTPRequestSmugglingCollector",
    "RequestSmugglingCollector",
    "RequestSmugglingPayloadGenerator",
    "RequestSmugglingSecurityAnalyzer",
    "RawHttpStreamProber",
    "RawHttpResponse",
    "RequestSmugglingResult",
    "RequestSmugglingSeverity",
    "RequestSmugglingTechnique",
    "RequestSmugglingMutationStrategy",
    "RaceConditionsCollector",
    "RaceConditionCollector",
    "RaceConditionPayloadGenerator",
    "RaceConditionSecurityAnalyzer",
    "ConcurrencyProber",
    "ConcurrencyProbeResponse",
    "RaceConditionResult",
    "RaceConditionSeverity",
    "RaceConditionTechnique",
    "ConcurrencyStrategy",
    "BusinessLogicCollector",
    "BusinessLogicFlawsCollector",
    "BusinessLogicPayloadGenerator",
    "BusinessLogicSecurityAnalyzer",
    "StatefulWorkflowProber",
    "BusinessLogicResult",
    "BusinessLogicSeverity",
    "BusinessLogicTechnique",
    "BusinessLogicMutationStrategy",
    "WorkflowStep",
    "WorkflowSequence",
    "BusinessLogicProbe",
    "BusinessLogicProbeResponse",
    "SSTICollector",
    "ServerSideTemplateInjectionCollector",
    "SSTIPayloadGenerator",
    "SSTISecurityAnalyzer",
    "SSTIProber",
    "SSTIProbe",
    "SSTIProbeResponse",
    "SSTIResult",
    "SSTISeverity",
    "SSTITechnique",
    "SSTIEngineFamily",
    "SSTIMutationStrategy",
    "CacheSecurityCollector",
    "WebCachePoisoningCollector",
    "CachePoisoningCollector",
    "WebCacheDeceptionCollector",
    "CacheSecurityPayloadGenerator",
    "CacheSecurityProber",
    "CacheSecurityAnalyzer",
    "CacheProbe",
    "CacheProbeResponse",
    "CacheSecurityResult",
    "CacheVulnerabilityType",
    "CacheSecurityTechnique",
    "CacheEngineFamily",
    "CacheEngine",
    "CacheStatus",
    "CacheMutationStrategy",
    "CacheSecurityMutationStrategy",
    "CacheSecuritySeverity",
    "CORSSecurityCollector",
    "CORSSecurityAnalyzer",
    "CORSHeadersCollector",
    "CORSCollector",
    "CORSMisconfigurationCollector",
    "HTTPHeaderAuditorCollector",
    "SecurityHeadersCollector",
    "HTTPHeaderCollector",
    "CORSPayloadGenerator",
    "CORSAnalyzer",
    "CORSProbe",
    "CORSProbeResponse",
    "CORSSecurityResult",
    "HeaderAuditResult",
    "CORSVulnerabilityType",
    "HeaderVulnerabilityType",
    "CORSMutationStrategy",
    "AuthBypassCollector",
    "AuthenticationBypassCollector",
    "CredentialAttackCollector",
    "BruteForceCollector",
    "DefaultCredentialsCollector",
    "JWTMisconfigurationCollector",
    "MFABypassCollector",
    "SessionFixationCollector",
    "AuthCollector",
    "AuthBypassPayloadGenerator",
    "AuthBypassProber",
    "AuthBypassAnalyzer",
    "TokenEntropyAnalyzer",
    "AuthBypassProbe",
    "AuthBypassProbeResponse",
    "AuthBypassResult",
    "AuthVulnerabilityType",
    "AuthBypassTechnique",
    "AuthTechnique",
    "AuthMutationStrategy",
    "AuthBypassMutationStrategy",
    "AuthStrategy",
    "AuthBypassSeverity",
    "AuthSeverity",
    "PrototypePollutionCollector",
    "ClientSideAttackCollector",
    "DOMClobberingCollector",
    "OpenRedirectCollector",
    "ClickjackingCollector",
    "ProtoPollutionCollector",
    "PrototypePollutionPayloadGenerator",
    "PrototypePollutionProber",
    "PrototypePollutionAnalyzer",
    "PrototypePollutionProbe",
    "PrototypePollutionProbeResponse",
    "PrototypePollutionResult",
    "ClientSideAttackResult",
    "PrototypePollutionVulnerabilityType",
    "ClientSideVulnerabilityType",
    "PrototypePollutionTechnique",
    "ClientSideTechnique",
    "PrototypePollutionMutationStrategy",
    "ClientSideMutationStrategy",
    "PrototypePollutionStrategy",
    "ClientSideStrategy",
    "PrototypePollutionSeverity",
    "ClientSideSeverity",
    "GadgetFramework",
]








