import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
from enum import Enum
from pydantic import BaseModel, Field

def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


class TaskCategory(str, Enum):
    """Categories of research tasks the planner can generate."""
    TECHNOLOGY_DISCOVERY = "Technology Discovery"
    API_DISCOVERY = "API Discovery"
    GRAPHQL_ANALYSIS = "GraphQL Analysis"
    AUTHENTICATION_ANALYSIS = "Authentication Analysis"
    AUTHORIZATION_ANALYSIS = "Authorization Analysis"
    BUSINESS_LOGIC_ANALYSIS = "Business Logic Analysis"
    JAVASCRIPT_ANALYSIS = "JavaScript Analysis"
    WORKFLOW_ANALYSIS = "Workflow Analysis"
    EVIDENCE_CORRELATION = "Evidence Correlation"
    INVESTIGATION_REVIEW = "Investigation Review"
    COVERAGE_IMPROVEMENT = "Coverage Improvement"


class ResearchTask(BaseModel):
    """A single recommended research action generated by the Research Planner."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str
    goal: str
    category: TaskCategory
    required_inputs: List[str] = Field(default_factory=list)
    expected_outputs: List[str] = Field(default_factory=list)
    priority: float = Field(0.5, ge=0.0, le=1.0)
    confidence: float = Field(0.5, ge=0.0, le=1.0)
    dependencies: List[str] = Field(default_factory=list)
    required_specialists: List[str] = Field(default_factory=list)
    estimated_duration_minutes: int = 5
    status: str = "PENDING"
    reason: str = ""
    supporting_evidence: List[str] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    created_at: str = Field(default_factory=_utc_now)


class CoverageGap(BaseModel):
    """Describes a specific area where analysis coverage is missing or weak."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    area: str
    description: str
    severity: float = Field(0.5, ge=0.0, le=1.0)
    category: TaskCategory = TaskCategory.COVERAGE_IMPROVEMENT
    related_assets: List[str] = Field(default_factory=list)


class CoverageReport(BaseModel):
    """Tracks analysis coverage across all mission dimensions."""
    endpoints_covered: int = 0
    endpoints_total: int = 0
    business_objects_covered: int = 0
    business_objects_total: int = 0
    workflows_covered: int = 0
    workflows_total: int = 0
    authentication_covered: bool = False
    authorization_covered: bool = False
    technologies_covered: int = 0
    technologies_total: int = 0
    overall_coverage: float = 0.0
    gaps: List[CoverageGap] = Field(default_factory=list)
    computed_at: str = Field(default_factory=_utc_now)

class PlanDependency(BaseModel):
    """Defines a dependency between two steps in the research plan."""
    source_step: str
    target_step: str
    is_hard_dependency: bool = True

class PlanStep(BaseModel):
    """Represents a single executable step within the research plan."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    description: str
    inputs: List[str] = Field(default_factory=list)
    outputs: List[str] = Field(default_factory=list)
    expected_artifacts: List[str] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list) # List of step names it depends on
    specialist_assigned: Optional[str] = None
    status: str = "PENDING"

class ResearchPlan(BaseModel):
    """The structured Research Plan generated from a Mission."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    mission_id: str
    objectives: List[str] = Field(default_factory=list)
    constraints: List[str] = Field(default_factory=list)
    scope: List[str] = Field(default_factory=list)
    policy: Dict[str, Any] = Field(default_factory=dict)
    
    steps: List[PlanStep] = Field(default_factory=list)
    dependencies: List[PlanDependency] = Field(default_factory=list)
    
    estimated_duration_minutes: int = 0
    priority: str = "NORMAL"
    status: str = "DRAFT"
    
    created_at: str = Field(default_factory=_utc_now)
    updated_at: str = Field(default_factory=_utc_now)
