"""
Canonical scan/research task templates for Argus.

Single source of truth for the recon+vulnerability task definitions consumed by
both the deterministic scan tier (argus.scanning.dag.ScanDAG) and the autonomous
planning tier (argus.planning.task_generator.TaskGenerator). Public names are
RECON_TEMPLATES / TOOL_TEMPLATES / SPECIALIST_TEMPLATES; the underscore-prefixed
names are retained as backward-compatible aliases for existing importers.
"""
from argus.planning.models import TaskCategory


# Concrete recon task templates
_RECON_TEMPLATES = {
    "subfinder": {
        "title": "Discover Subdomains",
        "goal": "Enumerate all subdomains in scope for the target.",
        "category": TaskCategory.TECHNOLOGY_DISCOVERY,
        "required_inputs": ["target"],
        "expected_outputs": ["subdomains"],
        "dependencies": [],
        "required_specialists": [],
        "metadata": {"tool_id": "subfinder"},
        "estimated_duration_minutes": 5,
        "priority": 0.95,
    },
    "httpx": {
        "title": "Fingerprint Live Hosts",
        "goal": "Probe subdomains to discover live HTTP/HTTPS hosts and fingerprint technologies.",
        "category": TaskCategory.TECHNOLOGY_DISCOVERY,
        "required_inputs": ["subdomains"],
        "expected_outputs": ["live_hosts", "technologies"],
        "dependencies": ["Discover Subdomains"],
        "required_specialists": [],
        "metadata": {"tool_id": "httpx"},
        "estimated_duration_minutes": 5,
        "priority": 0.90,
    },
    "katana_crawler": {
        "title": "Discover API Endpoints",
        "goal": "Enumerate and crawl endpoints on live hosts.",
        "category": TaskCategory.API_DISCOVERY,
        "required_inputs": ["live_hosts"],
        "expected_outputs": ["endpoints"],
        "dependencies": ["Fingerprint Live Hosts"],
        "required_specialists": [],
        "metadata": {"tool_id": "katana_crawler"},
        "estimated_duration_minutes": 10,
        "priority": 0.85,
    },
    "nuclei": {
        "title": "Scan Live Hosts",
        "goal": "Run automated vulnerability templates against live hosts.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["live_hosts"],
        "expected_outputs": ["vulnerabilities", "observations"],
        "dependencies": ["Fingerprint Live Hosts"],
        "required_specialists": [],
        "metadata": {"tool_id": "nuclei"},
        "estimated_duration_minutes": 15,
        "priority": 0.80,
    },
    "info_disclosure": {
        "title": "Probe Information Disclosure",
        "goal": "Probe live hosts and endpoints for exposed sensitive files (.git, .env, actuator, phpinfo, source maps) and extract leaked secrets/hostnames.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["live_hosts"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence", "subdomains"],
        "dependencies": ["Fingerprint Live Hosts"],
        "required_specialists": [],
        "metadata": {"tool_id": "info_disclosure"},
        "estimated_duration_minutes": 5,
        "priority": 0.82,
    },
    "access_control": {
        "title": "Analyze Access Control & IDOR",
        "goal": "Test authorization boundaries, horizontal IDOR, vertical privilege escalation, and proxy header bypasses across identities.",
        "category": TaskCategory.AUTHORIZATION_ANALYSIS,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "access_control"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "path_traversal": {
        "title": "Fuzz Path & Directory Traversal",
        "goal": "Actively fuzz discovered endpoint parameters and URL paths for directory traversal and arbitrary file disclosure vulnerabilities using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "path_traversal"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "sql_injection": {
        "title": "Fuzz SQL Injection",
        "goal": "Actively fuzz discovered endpoint parameters and HTTP headers for error-based, boolean-based, and time-based SQL injection vulnerabilities using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "sql_injection"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "xss": {
        "title": "Fuzz Cross-Site Scripting (XSS)",
        "goal": "Actively inject context-aware XSS payloads into discovered endpoint parameters and forms detecting reflected and stored XSS using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "xss"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "command_injection": {
        "title": "Fuzz OS Command Injection",
        "goal": "Actively fuzz discovered endpoint parameters and HTTP headers for result-based, time-based blind, and error-based OS command injection vulnerabilities using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "command_injection"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "ssrf": {
        "title": "Fuzz Server-Side Request Forgery (SSRF)",
        "goal": "Actively fuzz discovered endpoint parameters and HTTP headers for server-side request forgery, probing cloud metadata services, internal services, and blind differential timing using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "ssrf"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "oauth": {
        "title": "Analyze OAuth & OIDC Authentication",
        "goal": "Test OAuth/OIDC endpoints, token validation signatures/claims, and stateful session management using AuthenticatedHttpClient.",
        "category": TaskCategory.AUTHORIZATION_ANALYSIS,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "oauth"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "xml_parser_validation": {
        "title": "Validate XML Parser Security",
        "goal": "Actively fuzz discovered XML-accepting endpoints and parameters for external entity resolution, parameter entities, and recursive entity expansion misconfigurations using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "xml_parser_validation"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "deserialization": {
        "title": "Validate Insecure Deserialization",
        "goal": "Actively fuzz discovered endpoint parameters, bodies, headers, and cookies for insecure deserialization across multiple formats (Java, Python pickle, PHP, Ruby, .NET) using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "deserialization"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "graphql_security": {
        "title": "Validate GraphQL Security",
        "goal": "Actively test discovered GraphQL endpoints for introspection leakage, query depth/complexity DoS, query batching abuse, and field-level authorization bypass using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "graphql_security"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "websocket_security": {
        "title": "Validate WebSocket Security",
        "goal": "Actively test discovered WebSocket endpoints for Cross-Site WebSocket Hijacking (CSWSH), unauthenticated handshakes, message frame injection, and WebSocket DoS/rate-limiting resilience using AuthenticatedHttpClient and WebSocket handshake probers.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "websocket_security"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "request_smuggling": {
        "title": "Validate HTTP Request Smuggling",
        "goal": "Actively test discovered endpoints and upstream frontends for HTTP request smuggling (CL.TE, TE.CL, TE.TE, HTTP/2 downgrading) and boundary desynchronization.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "request_smuggling"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "race_conditions": {
        "title": "Validate Race Conditions & Concurrency",
        "goal": "Actively test discovered endpoints and state-changing workflows for race conditions, limit overruns, TOCTOU desynchronization, session concurrency, and partial state vulnerabilities using AuthenticatedHttpClient and concurrent multi-request synchronization probers.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "race_conditions"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "business_logic": {
        "title": "Validate Business Logic & State Machine Security",
        "goal": "Actively test discovered endpoints and multi-step workflows for price/quantity tampering, state transition skips, mass assignment, and coupon/voucher stacking using AuthenticatedHttpClient and stateful probers.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "business_logic"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "ssti": {
        "title": "Validate Server-Side Template Injection (SSTI)",
        "goal": "Actively test discovered endpoints and parameters for server-side template injection across Jinja2, Twig, Freemarker, Velocity, Mako, SpEL, ERB, and other template engines using AuthenticatedHttpClient and polyglot probers.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "ssti"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "cache_security": {
        "title": "Validate Web Cache Security & Cache Deception",
        "goal": "Actively probe discovered endpoints for Web Cache Poisoning (unkeyed headers/parameters, parameter cloaking, FAT GETs, method overrides) and Web Cache Deception using AuthenticatedHttpClient and differential probers.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "cache_security"},
        "estimated_duration_minutes": 10,
        "priority": 0.82,
    },
    "cors_security": {
        "title": "Validate CORS Configuration & HTTP Security Headers",
        "goal": "Probe discovered endpoints for CORS misconfigurations and audit HTTP security headers.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "cors_security"},
        "estimated_duration_minutes": 8,
        "priority": 0.83,
    },
    "file_upload": {
        "title": "Validate File Upload Security",
        "goal": "Actively test discovered endpoints for unrestricted executable uploads, MIME type bypasses, double extensions, polyglots, and path traversal in filenames using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "file_upload"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "api_security": {
        "title": "Validate REST & gRPC API Security",
        "goal": "Actively test discovered API endpoints for parameter tampering, mass assignment, rate limiting bypass, BOLA/IDOR, excessive data exposure, and method tampering using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "api_security"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "auth_bypass": {
        "title": "Validate Authentication Bypass & Credential Attacks",
        "goal": "Actively test discovered endpoints and authentication portals for brute force, account lockout, password reset abuse, MFA bypass, session fixation, JWT manipulation, and default credentials using AuthenticatedHttpClient.",
        "category": TaskCategory.AUTHENTICATION_ANALYSIS,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "auth_bypass"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
    "prototype_pollution": {
        "title": "Validate Prototype Pollution & Client-Side Attacks",
        "goal": "Actively test discovered endpoints for server-side/client-side prototype pollution, DOM clobbering, open redirect chains, and clickjacking vulnerabilities using AuthenticatedHttpClient.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_inputs": ["endpoints"],
        "expected_outputs": ["vulnerabilities", "observations", "evidence"],
        "dependencies": ["Discover API Endpoints"],
        "required_specialists": [],
        "metadata": {"tool_id": "prototype_pollution"},
        "estimated_duration_minutes": 10,
        "priority": 0.81,
    },
}

_TOOL_TEMPLATES = _RECON_TEMPLATES


# Specialist and fallback templates
_SPECIALIST_TEMPLATES = {
    TaskCategory.API_DISCOVERY: {
        "title": "Analyze API Endpoints",
        "goal": "Enumerate and analyze API endpoints for security issues.",
        "category": TaskCategory.API_DISCOVERY,
        "required_specialists": ["api_specialist"],
        "metadata": {"tool_id": "api_specialist"},
        "expected_outputs": ["api_inventory", "observations"],
        "dependencies": [],
        "estimated_duration_minutes": 10,
    },
    TaskCategory.GRAPHQL_ANALYSIS: {
        "title": "Analyze GraphQL Schema",
        "goal": "Introspect and analyze the GraphQL schema for vulnerabilities.",
        "category": TaskCategory.GRAPHQL_ANALYSIS,
        "required_specialists": ["graphql_specialist"],
        "metadata": {"tool_id": "graphql_specialist"},
        "expected_outputs": ["graphql_state", "observations"],
        "dependencies": [],
        "estimated_duration_minutes": 10,
    },
    TaskCategory.AUTHENTICATION_ANALYSIS: {
        "title": "Analyze Authentication Workflows",
        "goal": "Evaluate authentication mechanisms and session management.",
        "category": TaskCategory.AUTHENTICATION_ANALYSIS,
        "required_specialists": ["authentication_specialist"],
        "metadata": {"tool_id": "authentication_specialist"},
        "expected_outputs": ["authentication_state", "observations"],
        "dependencies": [],
        "estimated_duration_minutes": 10,
    },
    TaskCategory.AUTHORIZATION_ANALYSIS: {
        "title": "Analyze Authorization Relationships",
        "goal": "Build authorization graph and detect access control issues.",
        "category": TaskCategory.AUTHORIZATION_ANALYSIS,
        "required_specialists": ["authorization_specialist"],
        "metadata": {"tool_id": "authorization_specialist"},
        "expected_outputs": ["authorization_state", "observations"],
        "dependencies": ["Analyze Authentication Workflows"],
        "estimated_duration_minutes": 15,
    },
    TaskCategory.BUSINESS_LOGIC_ANALYSIS: {
        "title": "Analyze Business Logic Workflows",
        "goal": "Identify flaws in application-specific workflows.",
        "category": TaskCategory.BUSINESS_LOGIC_ANALYSIS,
        "required_specialists": ["business_logic_specialist"],
        "metadata": {"tool_id": "business_logic_specialist"},
        "expected_outputs": ["business_objects", "observations"],
        "dependencies": [],
        "estimated_duration_minutes": 15,
    },
    TaskCategory.JAVASCRIPT_ANALYSIS: {
        "title": "Analyze JavaScript Bundles",
        "goal": "Parse and analyze JavaScript bundles for secrets and endpoints.",
        "category": TaskCategory.JAVASCRIPT_ANALYSIS,
        "required_specialists": ["javascript_specialist"],
        "metadata": {"tool_id": "javascript_specialist"},
        "expected_outputs": ["javascript_state", "observations"],
        "dependencies": [],
        "estimated_duration_minutes": 10,
    },
    TaskCategory.EVIDENCE_CORRELATION: {
        "title": "Correlate Evidence",
        "goal": "Build correlations and evidence bundles from existing observations.",
        "category": TaskCategory.EVIDENCE_CORRELATION,
        "required_specialists": [],
        "metadata": {},
        "expected_outputs": ["Correlations", "Evidence Bundles"],
        "dependencies": [],
        "estimated_duration_minutes": 5,
    },
    TaskCategory.INVESTIGATION_REVIEW: {
        "title": "Review Pending Investigations",
        "goal": "Re-evaluate pending investigations with new evidence.",
        "category": TaskCategory.INVESTIGATION_REVIEW,
        "required_specialists": [],
        "metadata": {},
        "expected_outputs": ["Updated Investigations"],
        "dependencies": [],
        "estimated_duration_minutes": 5,
    },
    TaskCategory.COVERAGE_IMPROVEMENT: {
        "title": "Improve Coverage",
        "goal": "Fill coverage gaps identified by the coverage tracker.",
        "category": TaskCategory.COVERAGE_IMPROVEMENT,
        "required_specialists": [],
        "metadata": {},
        "expected_outputs": ["Additional Observations"],
        "dependencies": [],
        "estimated_duration_minutes": 10,
    },
}


# Public canonical names (preferred). The underscore-prefixed names above are
# retained for backward compatibility with existing importers.
RECON_TEMPLATES = _RECON_TEMPLATES
TOOL_TEMPLATES = _TOOL_TEMPLATES
SPECIALIST_TEMPLATES = _SPECIALIST_TEMPLATES

__all__ = [
    "RECON_TEMPLATES",
    "TOOL_TEMPLATES",
    "SPECIALIST_TEMPLATES",
    "_RECON_TEMPLATES",
    "_TOOL_TEMPLATES",
    "_SPECIALIST_TEMPLATES",
]
